language: python
python:
  - "3.8"
script: python lambda_function.py
deploy:
  provider: lambda
  function_name: "RingFitAdventure"
  region: "us-east-2"
  runtime: "python3.8"
  handler_name: "lambda_function.lambda_handler"