language: python
python:
  - "3.8"
deploy:
  provider: lambda
  function_name: "RingFitAdventure"
  region: "us-east-2"
  role: "arn:aws:iam::698425550551:role/lambda_basic_execution"
  runtime: "python3.8"
  handler_name: "lambda_function.lambda_handler"